/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 industrial-robot.glb -t 
*/

import type { JSX } from "react";
import Manipulator from "./industrial-robot-manipulator";
import { useIndustrialRobotContext } from "@/context/industrial-robot";
import { useGLTF } from "@react-three/drei";
import EndEffectors from "./industrial-robot-end-effectors";

export function IndustrialRobot(props: JSX.IntrinsicElements["group"]) {
  const { groupRef } = useIndustrialRobotContext();
  return (
    <group ref={groupRef} {...props} dispose={null}>
      <group name="Scene">
        <group name="Armature">
          {/* <primitive object={nodes.Bone} /> */}
          <Manipulator />
          <EndEffectors />
        </group>
        {/* <group name="pallet" position={[0, 0, 1.5]} scale={[0.6, 0.1, 0.4]}>
          <mesh
            name="Object_0"
            geometry={nodes.Object_0.geometry}
            material={materials.wood}
          />
          <mesh
            name="Object_0_1"
            geometry={nodes.Object_0_1.geometry}
            material={materials.incision}
          />
        </group>
        <group
          name="400×300×500"
          position={[0.925, 0.5, 0]}
          rotation={[-Math.PI, 0.01, -Math.PI]}
        >
          <mesh
            name="Cube014"
            geometry={nodes.Cube014.geometry}
            material={materials.box}
          />
          <mesh
            name="Cube014_1"
            geometry={nodes.Cube014_1.geometry}
            material={materials.scotch}
          />
        </group>
        <group name="400×300×500001" position={[0.925, 0.5, -0.45]}>
          <mesh
            name="Cube004"
            geometry={nodes.Cube004.geometry}
            material={materials.box}
          />
          <mesh
            name="Cube004_1"
            geometry={nodes.Cube004_1.geometry}
            material={materials.scotch}
          />
        </group>
        <group name="400×300×500002" position={[0.925, 0.5, -0.9]}>
          <mesh
            name="Cube006"
            geometry={nodes.Cube006.geometry}
            material={materials.box}
          />
          <mesh
            name="Cube006_1"
            geometry={nodes.Cube006_1.geometry}
            material={materials.scotch}
          />
        </group>
        <group name="400×300×500003" position={[0.925, 0.5, -1.35]}>
          <mesh
            name="Cube009"
            geometry={nodes.Cube009.geometry}
            material={materials.box}
          />
          <mesh
            name="Cube009_1"
            geometry={nodes.Cube009_1.geometry}
            material={materials.scotch}
          />
        </group>
        <mesh
          name="glass-1"
          geometry={nodes["glass-1"].geometry}
          material={nodes["glass-1"].material}
          position={[0.925, 0.02, 0]}
          scale={[0.5, 0.01, 0.5]}
        />
        <mesh
          name="glass-2"
          geometry={nodes["glass-2"].geometry}
          material={nodes["glass-2"].material}
          position={[0.925, 0.02, -1.1]}
          scale={[0.5, 0.01, 0.5]}
        /> */}
      </group>
    </group>
  );
}

useGLTF.preload("/assets/industrial-robot.glb");
