/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 industrial-robot.glb -t 
*/

import * as THREE from 'three'
import React, { useEffect, type JSX } from 'react'
import { useGraph } from '@react-three/fiber'
import { useGLTF, useAnimations } from '@react-three/drei'
import { type GLTF, SkeletonUtils } from 'three-stdlib'
import { useAppSelector } from '@/store/hooks'


type ActionName = 'draw-line'

interface GLTFAction extends THREE.AnimationClip {
  name: ActionName
}

type GLTFResult = GLTF & {
  nodes: {
    Cylinder022: THREE.Mesh
    Mesh: THREE.Mesh
    Mesh_1: THREE.Mesh
    Cylinder058: THREE.Mesh
    Cylinder058_1: THREE.Mesh
    Cylinder036: THREE.Mesh
    Cylinder036_1: THREE.Mesh
    Cylinder011: THREE.Mesh
    Cylinder011_1: THREE.Mesh
    Cylinder002: THREE.Mesh
    Cylinder002_1: THREE.Mesh
    Cylinder_1: THREE.Mesh
    Cylinder_2: THREE.Mesh
    Bone: THREE.Bone
  }
  materials: {
    metall: THREE.MeshStandardMaterial
    white: THREE.MeshStandardMaterial
    rubber: THREE.MeshStandardMaterial
  }
  animations: GLTFAction[]
}

export function Model(props: JSX.IntrinsicElements['group']) {
  const group = React.useRef<THREE.Group>(new THREE.Group())
  const { scene, animations } = useGLTF('/assets/industrial-robot.glb')
  const clone = React.useMemo(() => SkeletonUtils.clone(scene), [scene])
  const { nodes } = useGraph(clone) as unknown as GLTFResult
  const { actions } = useAnimations(animations, group)
  const { robotAnimation } = useAppSelector((state) => state.industrialRobotSlice)

  useEffect(() => {
    actions[robotAnimation]?.play();

    return () => {
      actions[robotAnimation]?.stop();
    }
  }, [actions, robotAnimation]);
  return (
    <group ref={group} {...props} dispose={null}>
      <group name="Scene">
        <group name="Armature">
          <primitive object={nodes.Bone} />
        </group>
      </group>
    </group>
  )
}

useGLTF.preload('/assets/industrial-robot.glb')
